function likelihood_by_state = get_likelihood_by_state(state_number, stateV_length, ...
    is_spike_at_time_t, tet_ind, tet_sum, marks, ...
    mark_spikes_to_linear_position_time_bins_index, gaussian_kernel_position_estimator, position_occupancy, estimated_rate_by_tetrode, dt, smker)
likelihood_by_tetrode = zeros(stateV_length, length(is_spike_at_time_t));
for j = 1:length(is_spike_at_time_t)
    tetrode_ind = find(tet_ind(is_spike_at_time_t(j), :));
    likelihood_by_tetrode(:, j) = get_likelihood_by_tetrode(tet_sum(is_spike_at_time_t(j), tetrode_ind), ...
        marks{tetrode_ind}, mark_spikes_to_linear_position_time_bins_index{tetrode_ind, state_number}, ...
        gaussian_kernel_position_estimator{tetrode_ind, state_number}, position_occupancy{state_number}, ...
        estimated_rate_by_tetrode{tetrode_ind, state_number}, dt, smker);
end
likelihood_by_state = prod(likelihood_by_tetrode, 2);
likelihood_by_state = likelihood_by_state ./ sum(likelihood_by_state);
end